[versions]

java-source = '21'

java-toolchain = '21'

kotlin = '2.2.0'

metro = '0.5.3'

[plugins]

kotlin-jvm = { id = 'org.jetbrains.kotlin.jvm', version.ref = 'kotlin' }

metro = { id = 'dev.zacsweers.metro', version.ref = 'metro' }
