[versions]

java-source = '21'

java-toolchain = '21'

#kotlin = '2.1.21'
kotlin = '2.2.0-RC3'

#metro = '0.3.8'
metro = '0.4.0-SNAPSHOT'

[plugins]

kotlin-jvm = { id = 'org.jetbrains.kotlin.jvm', version.ref = 'kotlin' }

metro = { id = 'dev.zacsweers.metro', version.ref = 'metro' }
